System.register("chunks:///_virtual/app-module-game",["./AppModuleGame.ts","./PropType.ts","./BlockComponent.ts","./BoardComponent.ts","./BlockEntity.ts","./BoardSingleton.ts","./DataSingleton.ts","./ClearSystem.ts","./DragSystem.ts","./DropSystem.ts","./SpawnSystem.ts","./GameService.ts","./PageGame.ts","./PaperGame.ts","./PopGameOver.ts","./PopPause.ts","./PopProp.ts"],(function(){return{setters:[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],execute:function(){}}}));

System.register("chunks:///_virtual/AppModuleGame.ts",["./rollupPluginModLoBabelHelpers.js","cc","./BaseModule.ts","./PageGame.ts"],(function(e){var o,n,t,u,i;return{setters:[function(e){o=e.inheritsLoose},function(e){n=e.cclegacy},function(e){t=e.module,u=e.BaseModule},function(e){i=e.PageGame}],execute:function(){var r;n._RF.push({},"1d601q6BL9HVYkeV65PQLID","AppModuleGame",void 0);e("Module",t("Game")(r=function(e){function n(){return e.apply(this,arguments)||this}o(n,e);var t=n.prototype;return t.init=function(e,o,n){this.ui.show({view:i,onShow:e,onError:o,onProgress:n})},t.onLoad=function(){},n}(u))||r);n._RF.pop()}}}));

System.register("chunks:///_virtual/BlockComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc","./cc-ecs.ts","./EcsManager.ts","./EcsComponent.ts"],(function(n){var o,t,c,e;return{setters:[function(n){o=n.inheritsLoose},function(n){t=n.cclegacy},null,function(n){c=n.ecsclass},function(n){e=n.EcsComponent}],execute:function(){var s,l;t._RF.push({},"b33cft+dBxNIqjipN695leD","BlockComponent",void 0);n("BlockComponent",c("BlockComponent")(((l=function(n){function t(){for(var o,t=arguments.length,c=new Array(t),e=0;e<t;e++)c[e]=arguments[e];return(o=n.call.apply(n,[this].concat(c))||this).type=1,o.col=0,o.row=0,o.targetCol=0,o.isDropping=!1,o.isDragging=!1,o}return o(t,n),t}(e)).allowRecycling=!0,s=l))||s);t._RF.pop()}}}));

System.register("chunks:///_virtual/BlockEntity.ts",["./rollupPluginModLoBabelHelpers.js","cc","./index.ts","./EcsEntity.ts"],(function(t){var n,c,i;return{setters:[function(t){n=t.inheritsLoose},function(t){c=t.cclegacy},null,function(t){i=t.EcsEntity}],execute:function(){c._RF.push({},"d055d+Br/ZHooYUQw5W4YcA","BlockEntity",void 0),t("BlockEntity",function(t){function c(){return t.apply(this,arguments)||this}return n(c,t),c}(i)).recovery=!0,c._RF.pop()}}}));

System.register("chunks:///_virtual/BoardComponent.ts",["./rollupPluginModLoBabelHelpers.js","cc","./index.ts","./EcsManager.ts","./EcsComponent.ts"],(function(n){var o,t,e,c;return{setters:[function(n){o=n.inheritsLoose},function(n){t=n.cclegacy},null,function(n){e=n.ecsclass},function(n){c=n.EcsComponent}],execute:function(){var r;t._RF.push({},"64a5cuWRSJFA5KGKO41wUk3","BoardComponent",void 0);n("BoardComponent",e("BoardComponent")(r=function(n){function t(){for(var o,t=arguments.length,e=new Array(t),c=0;c<t;c++)e[c]=arguments[c];return(o=n.call.apply(n,[this].concat(e))||this).grid=[],o.rows=10,o.cols=8,o.cellSize=110,o}return o(t,n),t}(c))||r);t._RF.pop()}}}));

System.register("chunks:///_virtual/BoardSingleton.ts",["./rollupPluginModLoBabelHelpers.js","cc","./index.ts","./EcsManager.ts","./EcsSingleton.ts"],(function(n){var e,t,o,i;return{setters:[function(n){e=n.inheritsLoose},function(n){t=n.cclegacy},null,function(n){o=n.ecsclass},function(n){i=n.EcsSingleton}],execute:function(){var r;t._RF.push({},"9807dMBLvVHA48P1gchG0sx","BoardSingleton",void 0);n("BoardSingleton",o("BoardSingleton")(r=function(n){function t(e){var t;return(t=n.call(this)||this).COLS=8,t.ROWS=10,t.grid=[],t.score=0,t.gameOver=!1,t.module=e,t}return e(t,n),t}(i))||r);t._RF.pop()}}}));

System.register("chunks:///_virtual/ClearSystem.ts",["./rollupPluginModLoBabelHelpers.js","cc","./index.ts","./EcsSystem.ts"],(function(t){var e,s,n;return{setters:[function(t){e=t.inheritsLoose},function(t){s=t.cclegacy},null,function(t){n=t.EcsSystem}],execute:function(){s._RF.push({},"294f5X/Vk9KHLsJF4Z1vWNu","ClearSystem",void 0);t("ClearSystem",function(t){function s(){return t.apply(this,arguments)||this}return e(s,t),s}(n));s._RF.pop()}}}));

System.register("chunks:///_virtual/DataSingleton.ts",["./rollupPluginModLoBabelHelpers.js","cc","./index.ts","./EcsManager.ts","./EcsSingleton.ts"],(function(n){var t,e,o,i;return{setters:[function(n){t=n.inheritsLoose},function(n){e=n.cclegacy},null,function(n){o=n.ecsclass},function(n){i=n.EcsSingleton}],execute:function(){var s;e._RF.push({},"5e785d7zdtIZouzlsu5wjF1","DataSingleton",void 0);n("DataSingleton",o("DataSingleton")(s=function(n){function e(t){var e;return(e=n.call(this)||this).over=!1,e.module=t,e}return t(e,n),e}(i))||s);e._RF.pop()}}}));

System.register("chunks:///_virtual/DragSystem.ts",["./rollupPluginModLoBabelHelpers.js","cc","./index.ts","./EcsSystem.ts"],(function(t){var e,n,s;return{setters:[function(t){e=t.inheritsLoose},function(t){n=t.cclegacy},null,function(t){s=t.EcsSystem}],execute:function(){n._RF.push({},"eb80db9F31Eh5nc//EWV4H8","DragSystem",void 0);t("DragSystem",function(t){function n(){return t.apply(this,arguments)||this}return e(n,t),n}(s));n._RF.pop()}}}));

System.register("chunks:///_virtual/DropSystem.ts",["./rollupPluginModLoBabelHelpers.js","cc","./index.ts","./EcsSystem.ts"],(function(t){var e,n,s;return{setters:[function(t){e=t.inheritsLoose},function(t){n=t.cclegacy},null,function(t){s=t.EcsSystem}],execute:function(){n._RF.push({},"f5633QvcaJFGIR4k40BdWLC","DropSystem",void 0);t("DropSystem",function(t){function n(){return t.apply(this,arguments)||this}return e(n,t),n}(s));n._RF.pop()}}}));

System.register("chunks:///_virtual/GameService.ts",["./rollupPluginModLoBabelHelpers.js","cc","./GlobalData.ts","./BaseService.ts","./XForge.ts"],(function(e){var t,n,o,i,c;return{setters:[function(e){t=e.inheritsLoose},function(e){n=e.cclegacy},function(e){o=e.GlobalData},function(e){i=e.BaseService},function(e){c=e.app}],execute:function(){n._RF.push({},"d2205Taf5pHHJ75f26HwTLv","GameService",void 0);var r=e("ClearBlockEvent",(function(e){this.node=e}));e("GameService",function(e){function n(){return e.apply(this,arguments)||this}t(n,e);var i=n.prototype;return i.clearBlock=function(e){this.event.emit(new r(e))},i.nextLevel=function(){c.global.useModel(o).level++},n}(i));n._RF.pop()}}}));

System.register("chunks:///_virtual/PageGame.ts",["./rollupPluginModLoBabelHelpers.js","cc","./BaseView.ts","./PaperGame.ts","./BoardSingleton.ts","./index.ts","./PopGameOver.ts","./SpawnSystem.ts","./DropSystem.ts","./ClearSystem.ts","./DragSystem.ts","./GameService.ts","./EcsWorld.ts"],(function(e){var t,n,i,o,r,s,a,c,u,l,f,d,m,p,h,S,g,w,y;return{setters:[function(e){t=e.applyDecoratedDescriptor,n=e.inheritsLoose,i=e.initializerDefineProperty,o=e.assertThisInitialized},function(e){r=e.cclegacy,s=e._decorator,a=e.Prefab,c=e.NodePool,u=e.instantiate},function(e){l=e.BaseView},function(e){f=e.PaperGame},function(e){d=e.BoardSingleton},null,function(e){m=e.PopGameOver},function(e){p=e.SpawnSystem},function(e){h=e.DropSystem},function(e){S=e.ClearSystem},function(e){g=e.DragSystem},function(e){w=e.GameService},function(e){y=e.EcsWorld}],execute:function(){var P,b,v,k,G;r._RF.push({},"769ba/AS3NJ5pYkUxRJpAQ2","PageGame",void 0);var D=s.ccclass,B=s.property;e("PageGame",(P=D("PageGame"),b=B(a),P((G=t((k=function(e){function t(){for(var t,n=arguments.length,r=new Array(n),s=0;s<n;s++)r[s]=arguments[s];return t=e.call.apply(e,[this].concat(r))||this,i(t,"blockPrefab",G,o(t)),t.blockPool=new c("BlockPool"),t.slow=1,t}n(t,e),t.beforeShow=function(e,t){return new window.Promise((function(t,n){e.ui.preload(f,t)}))};var r=t.prototype;return r.start=function(){y.inst.addSingleton(new d(this.module)),y.inst.addSystem(p),y.inst.addSystem(S),y.inst.addSystem(g),y.inst.addSystem(h),this.initCache(),this.initView()},r.onShow=function(e){this.module.ui.show({view:f})},r.update=function(e){var t=this;y.inst.getSingleton(d).gameOver?(this.slow+=.1,y.inst.execute(e/this.slow)):(y.inst.execute(e),!0===y.inst.getSingleton(d).gameOver&&this.scheduleOnce((function(){t.module.ui.show({view:m})}),.3))},r.initCache=function(){for(var e=0;e<30;e++){var t=u(this.blockPrefab);this.blockPool.put(t)}},r.getBlock=function(){var e=this.blockPool.get();return!e&&this.blockPrefab&&(e=u(this.blockPrefab)),e},r.initView=function(){},r.beforeHide=function(){},r.onHide=function(){return null},r.onDestroy=function(){y.inst.clear(),this.module.useService(w).event.targetOff(this)},t}(l)).prototype,"blockPrefab",[b],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),v=k))||v));r._RF.pop()}}}));

System.register("chunks:///_virtual/PaperGame.ts",["./rollupPluginModLoBabelHelpers.js","cc","./BaseView.ts","./PopPause.ts","./PopProp.ts","./index4.ts","./XForge.ts","./GlobalData.ts","./PropType.ts"],(function(e){var t,n,o,i,r,l,a,u,c,s,p,f,h,b,m,v;return{setters:[function(e){t=e.applyDecoratedDescriptor,n=e.inheritsLoose,o=e.initializerDefineProperty,i=e.assertThisInitialized},function(e){r=e.cclegacy,l=e._decorator,a=e.Label},function(e){u=e.BaseView},function(e){c=e.PopPause},function(e){s=e.PopProp},function(e){p=e.bindStore,f=e.watchStore,h=e.stopWatch},function(e){b=e.app},function(e){m=e.GlobalData},function(e){v=e.PropType}],execute:function(){var g,d,y,w,P,L,x,H,M,z,B;r._RF.push({},"c12afUr/UBOfZSArFAOzkcq","PaperGame",void 0);var D=l.ccclass,G=l.property;e("PaperGame",(g=D("PaperGame"),d=G(a),y=G(a),w=G(a),P=G(a),g((H=t((x=function(e){function t(){for(var t,n=arguments.length,r=new Array(n),l=0;l<n;l++)r[l]=arguments[l];return t=e.call.apply(e,[this].concat(r))||this,o(t,"curLevel",H,i(t)),o(t,"nextLevel",M,i(t)),o(t,"txtMobile",z,i(t)),o(t,"txtHammer",B,i(t)),t}n(t,e);var r=t.prototype;return r.onLoad=function(){var e=b.global.useModel(m);p(this.curLevel,"string",(function(){return""+e.level})),p(this.nextLevel,"string",(function(){return""+(e.level+1)})),p(this.txtMobile,"string",(function(){return""+e.mobile})),p(this.txtHammer,"string",(function(){return""+e.hammer})),f(this.onLevelChange,this)},t.beforeShow=function(e,t){return new window.Promise((function(e,t){e()}))},r.onShow=function(e){},r.onLevelChange=function(){var e=b.global.useModel(m);this.log("Level changed!",e.level)},r.onBtnPause=function(){b.global.sound.playEffect("click"),this.module.ui.show({view:c})},r.onBtnHammer=function(){b.global.sound.playEffect("click"),this.module.ui.show({view:s,data:{propType:v.Hammer}})},r.onBtnMobile=function(){b.global.sound.playEffect("click"),this.module.ui.show({view:s,data:{propType:v.Mobile}})},r.beforeHide=function(){},r.onHide=function(){return null},r.onDestroy=function(){h(this.onLevelChange,this)},t}(u)).prototype,"curLevel",[d],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),M=t(x.prototype,"nextLevel",[y],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),z=t(x.prototype,"txtMobile",[w],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),B=t(x.prototype,"txtHammer",[P],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),L=x))||L));r._RF.pop()}}}));

System.register("chunks:///_virtual/PopGameOver.ts",["./rollupPluginModLoBabelHelpers.js","cc","./BaseView.ts","./app.ts","./UIManager.ts","./XForge.ts"],(function(e){var n,o,t,i,r,u,a;return{setters:[function(e){n=e.inheritsLoose},function(e){o=e.cclegacy,t=e._decorator},function(e){i=e.BaseView},function(e){r=e.ModuleNames},function(e){u=e.UIManager},function(e){a=e.app}],execute:function(){var c;o._RF.push({},"8bee25lHCtOZJRRJDXGuOwE","PopGameOver",void 0);var s=t.ccclass;t.property,e("PopGameOver",s("PopGameOver")(c=function(e){function o(){return e.apply(this,arguments)||this}n(o,e),o.beforeShow=function(e,n){return new window.Promise((function(e,n){e()}))};var t=o.prototype;return t.onShow=function(e){},t.hide=function(){this.module.ui.hide(this)},t.beforeHide=function(){var e=u.addLoading();a.loadModule({name:r.Main,onLoaded:function(){a.unloadModule(r.Game),u.removeLoading(e)}})},t.onHide=function(){return null},o}(i))||c);o._RF.pop()}}}));

System.register("chunks:///_virtual/PopPause.ts",["./rollupPluginModLoBabelHelpers.js","cc","./BaseView.ts","./UIManager.ts","./app.ts","./XForge.ts"],(function(n){var o,e,t,i,u,c,a;return{setters:[function(n){o=n.inheritsLoose},function(n){e=n.cclegacy,t=n._decorator},function(n){i=n.BaseView},function(n){u=n.UIManager},function(n){c=n.ModuleNames},function(n){a=n.app}],execute:function(){var r;e._RF.push({},"4297cvW1rRM+4PrdhnSBGJE","PopPause",void 0);var s=t.ccclass;t.property,n("PopPause",s("PopPause")(r=function(n){function e(){return n.apply(this,arguments)||this}o(e,n),e.beforeShow=function(n,o){return new window.Promise((function(n,o){n()}))};var t=e.prototype;return t.onShow=function(n){},t.onBtnContinue=function(){a.global.sound.playEffect("click"),this.hide()},t.onBtnRestart=function(){a.global.sound.playEffect("click"),this.hide()},t.onBtnRetrun=function(){a.global.sound.playEffect("click");var n=u.addLoading();a.loadModule({name:c.Main,onLoaded:function(){a.unloadModule(c.Game),u.removeLoading(n)}})},t.hide=function(){a.global.sound.playEffect("click"),this.module.ui.hide(this)},t.beforeHide=function(){},t.onHide=function(){return null},e}(i))||r);e._RF.pop()}}}));

System.register("chunks:///_virtual/PopProp.ts",["./rollupPluginModLoBabelHelpers.js","cc","./BaseView.ts","./index3.ts","./GlobalData.ts","./XForge.ts","./index4.ts","./PropType.ts","./cc-store.ts","./MiniSDK.ts"],(function(o){var n,t,e,i,r,a,l,c,u,p,s,f,m,h,g,d,b;return{setters:[function(o){n=o.applyDecoratedDescriptor,t=o.inheritsLoose,e=o.initializerDefineProperty,i=o.assertThisInitialized},function(o){r=o.cclegacy,a=o._decorator,l=o.Label,c=o.Sprite,u=o.SpriteFrame},function(o){p=o.BaseView},null,function(o){s=o.GlobalData},function(o){f=o.app},function(o){m=o.bindStore,h=o.watchStore,g=o.stopWatch},function(o){d=o.PropType},null,function(o){b=o.miniSDK}],execute:function(){var y,D,w,v,P,S,T;r._RF.push({},"176760DMvRKDb2YR86VnwMz","PopProp",void 0);var M=a.ccclass,x=a.property;o("PopProp",(y=M("PopProp"),D=x(l),w=x(c),y((S=n((P=function(o){function n(){for(var n,t=arguments.length,r=new Array(t),a=0;a<t;a++)r[a]=arguments[a];return n=o.call.apply(o,[this].concat(r))||this,e(n,"txtNum",S,i(n)),e(n,"imgIcon",T,i(n)),n.gameData=void 0,n.propType=void 0,n}t(n,o);var r=n.prototype;return r.onLoad=function(){this.gameData=f.global.useModel(s)},n.beforeShow=function(o,n){return new window.Promise((function(o,n){o()}))},r.onShow=function(o){var n=this;this.propType=o.propType,m(this.txtNum,"string",(function(){return""+(n.propType===d.Mobile?n.gameData.mobile:n.gameData.hammer)})),h(this.onNumChange,this),this.loadIcon()},r.loadIcon=function(){var o=this,n="content/image/common/"+(this.propType===d.Mobile?"mobile":"hammer")+"/spriteFrame";f.global.loadAsset(n,u,(function(n){n&&(o.imgIcon.spriteFrame=n)}))},r.onNumChange=function(){},r.onBtnClaim=function(){var o=this;f.global.sound.playEffect("click"),b.showRewardedVideoAd({onShow:function(){o.log("广告开始播放")},onError:function(n){o.log("广告加载失败",n)},onClose:function(n){n?(o.log("广告播放完成，发放奖励"),o.propType===d.Mobile?o.gameData.mobile+=1:o.propType===d.Hammer&&(o.gameData.hammer+=1),o.hide()):o.log("用户中途关闭，未发放奖励")}})},r.hide=function(){f.global.sound.playEffect("click"),this.module.ui.hide(this)},r.beforeHide=function(){},r.onHide=function(){return null},r.onDestroy=function(){g(this.onNumChange,this)},n}(p)).prototype,"txtNum",[D],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),T=n(P.prototype,"imgIcon",[w],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),v=P))||v));r._RF.pop()}}}));

System.register("chunks:///_virtual/PropType.ts",["cc"],(function(e){var r;return{setters:[function(e){r=e.cclegacy}],execute:function(){r._RF.push({},"2966cAw6m1N7pBCkwqvfMQB","PropType",void 0);e("PropType",function(e){return e[e.None=0]="None",e[e.Hammer=1]="Hammer",e[e.Mobile=2]="Mobile",e}({}));r._RF.pop()}}}));

System.register("chunks:///_virtual/SpawnSystem.ts",["./rollupPluginModLoBabelHelpers.js","cc","./index.ts","./EcsSystem.ts"],(function(t){var n,e,s;return{setters:[function(t){n=t.inheritsLoose},function(t){e=t.cclegacy},null,function(t){s=t.EcsSystem}],execute:function(){e._RF.push({},"06a5bpPvk9LJKtiOa8P71UW","SpawnSystem",void 0);t("SpawnSystem",function(t){function e(){return t.apply(this,arguments)||this}return n(e,t),e}(s));e._RF.pop()}}}));

(function(r) {
  r('virtual:///prerequisite-imports/app-module-game', 'chunks:///_virtual/app-module-game'); 
})(function(mid, cid) {
    System.register(mid, [cid], function (_export, _context) {
    return {
        setters: [function(_m) {
            var _exportObj = {};

            for (var _key in _m) {
              if (_key !== "default" && _key !== "__esModule") _exportObj[_key] = _m[_key];
            }
      
            _export(_exportObj);
        }],
        execute: function () { }
    };
    });
});