System.register("chunks:///_virtual/app-module-main",["./AppModuleMain.ts","./PageMain.ts","./PaperMain.ts","./PopSetting.ts"],(function(){return{setters:[null,null,null,null],execute:function(){}}}));

System.register("chunks:///_virtual/AppModuleMain.ts",["./rollupPluginModLoBabelHelpers.js","cc","./BaseModule.ts","./PageMain.ts"],(function(n){var o,e,t,i,u;return{setters:[function(n){o=n.inheritsLoose},function(n){e=n.cclegacy},function(n){t=n.module,i=n.BaseModule},function(n){u=n.PageMain}],execute:function(){var r;e._RF.push({},"91b55Ojse9INYdu6wwzW012","AppModuleMain",void 0);n("Module",t("Main")(r=function(n){function e(){return n.apply(this,arguments)||this}o(e,n);var t=e.prototype;return t.init=function(n,o,e){this.ui.show({view:u,onShow:n,onError:o,onProgress:e})},t.onLoad=function(){},e}(i))||r);e._RF.pop()}}}));

System.register("chunks:///_virtual/PageMain.ts",["./rollupPluginModLoBabelHelpers.js","cc","./BaseView.ts","./PaperMain.ts"],(function(n){var e,i,o,t,r;return{setters:[function(n){e=n.inheritsLoose},function(n){i=n.cclegacy,o=n._decorator},function(n){t=n.BaseView},function(n){r=n.PaperMain}],execute:function(){var u;i._RF.push({},"86354Q13CxH0J6qjmFMUyh6","PageMain",void 0);var a=o.ccclass;o.property,n("PageMain",a("PageMain")(u=function(n){function i(){return n.apply(this,arguments)||this}e(i,n),i.beforeShow=function(n,e){return new window.Promise((function(e,i){n.ui.preload(r,e)}))};var o=i.prototype;return o.onShow=function(n){this.module.ui.show({view:r})},o.beforeHide=function(){},o.onHide=function(){return null},i}(t))||u);i._RF.pop()}}}));

System.register("chunks:///_virtual/PaperMain.ts",["./rollupPluginModLoBabelHelpers.js","cc","./BaseView.ts","./UIManager.ts","./XForge.ts","./app.ts","./GlobalData.ts","./index4.ts","./PopSetting.ts","./index3.ts","./MiniSDK.ts"],(function(n){var e,t,i,o,a,r,l,c,u,s,f,d,p,g,b,h,v,M;return{setters:[function(n){e=n.applyDecoratedDescriptor,t=n.inheritsLoose,i=n.initializerDefineProperty,o=n.assertThisInitialized},function(n){a=n.cclegacy,r=n._decorator,l=n.Label,c=n.Node},function(n){u=n.BaseView},function(n){s=n.UIManager},function(n){f=n.app},function(n){d=n.ModuleNames},function(n){p=n.GlobalData},function(n){g=n.bindStore,b=n.watchStore,h=n.stopWatch},function(n){v=n.PopSetting},null,function(n){M=n.miniSDK}],execute:function(){var S,y,L,m,w,P,D;a._RF.push({},"463cfCmpJtMc74rUeG08cz6","PaperMain",void 0);var B=r.ccclass,x=r.property;n("PaperMain",(S=B("PaperMain"),y=x(l),L=x(c),S((P=e((w=function(n){function e(){for(var e,t=arguments.length,a=new Array(t),r=0;r<t;r++)a[r]=arguments[r];return e=n.call.apply(n,[this].concat(a))||this,i(e,"txtLevel",P,o(e)),i(e,"btnSidebar",D,o(e)),e}t(e,n);var a=e.prototype;return a.onLoad=function(){var n=f.global.useModel(p);g(this.txtLevel,"string",(function(){return""+n.level})),b(this.onLevelChange,this),this.btnSidebar.active=M.isByteMiniGame()},e.beforeShow=function(n,e){return new window.Promise((function(n,e){n()}))},a.onShow=function(n){},a.onLevelChange=function(){var n=f.global.useModel(p);this.log("Level changed!",n.level)},a.onBtnGameStart=function(){f.global.sound.playEffect("click");var n=s.addLoading();f.loadModule({name:d.Game,onLoaded:function(){f.unloadModule(d.Main),s.removeLoading(n)}})},a.onBtnSetting=function(){f.global.sound.playEffect("click"),this.module.ui.show({view:v})},a.onBtnSidebar=function(){M.navigateToScene()},a.beforeHide=function(){},a.onHide=function(){return null},a.onDestroy=function(){h(this.onLevelChange,this)},e}(u)).prototype,"txtLevel",[y],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),D=e(w.prototype,"btnSidebar",[L],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),m=w))||m));a._RF.pop()}}}));

System.register("chunks:///_virtual/PopSetting.ts",["./rollupPluginModLoBabelHelpers.js","cc","./BaseView.ts","./XForge.ts","./SoundManager.ts","./GlobalData.ts"],(function(o){var e,t,n,i,l,a,g,c,s,u,r;return{setters:[function(o){e=o.applyDecoratedDescriptor,t=o.inheritsLoose,n=o.initializerDefineProperty,i=o.assertThisInitialized},function(o){l=o.cclegacy,a=o._decorator,g=o.Toggle},function(o){c=o.BaseView},function(o){s=o.app},function(o){u=o.SoundManager},function(o){r=o.GlobalData}],execute:function(){var h,f,d,p,b,S,k,m,y;l._RF.push({},"f112bRXNWpL2r7oXLbozNiB","PopSetting",void 0);var M=a.ccclass,v=a.property;o("PopSetting",(h=M("PopSetting"),f=v(g),d=v(g),p=v(g),h((k=e((S=function(o){function e(){for(var e,t=arguments.length,l=new Array(t),a=0;a<t;a++)l[a]=arguments[a];return e=o.call.apply(o,[this].concat(l))||this,n(e,"toggleSound",k,i(e)),n(e,"toggleMusic",m,i(e)),n(e,"toggleShock",y,i(e)),e.gameData=null,e}t(e,o);var l=e.prototype;return l.onLoad=function(){this.gameData=s.global.useModel(r)},e.beforeShow=function(o,e){return new window.Promise((function(o,e){o()}))},l.onShow=function(o){this.loadSettings(),this.toggleSound.node.on("toggle",this.onSoundToggle,this),this.toggleMusic.node.on("toggle",this.onMusicToggle,this),this.toggleShock.node.on("toggle",this.onShockToggle,this)},l.loadSettings=function(){var o=this.gameData.effectEnabled;this.toggleSound.isChecked=o;var e=this.gameData.musicEnabled;this.toggleMusic.isChecked=e;var t=this.gameData.shockEnabled;this.toggleShock.isChecked=t},l.onSoundToggle=function(o){s.global.sound.playEffect("click");var e=o.isChecked;u.effectVolumeScale=e?1:0,this.gameData.effectEnabled=e},l.onMusicToggle=function(o){s.global.sound.playEffect("click");var e=o.isChecked;u.musicVolumeScale=e?1:0,this.gameData.musicEnabled=e,e?s.global.sound.playMusic("bgm"):s.global.sound.stopMusic()},l.onShockToggle=function(o){s.global.sound.playEffect("click");var e=o.isChecked;this.gameData.shockEnabled=e},l.hide=function(){s.global.sound.playEffect("click"),this.module.ui.hide(this)},l.beforeHide=function(){this.toggleSound.node.off("toggle",this.onSoundToggle,this),this.toggleMusic.node.off("toggle",this.onMusicToggle,this),this.toggleShock.node.off("toggle",this.onShockToggle,this)},l.onHide=function(){return null},e}(c)).prototype,"toggleSound",[f],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),m=e(S.prototype,"toggleMusic",[d],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),y=e(S.prototype,"toggleShock",[p],{configurable:!0,enumerable:!0,writable:!0,initializer:function(){return null}}),b=S))||b));l._RF.pop()}}}));

(function(r) {
  r('virtual:///prerequisite-imports/app-module-main', 'chunks:///_virtual/app-module-main'); 
})(function(mid, cid) {
    System.register(mid, [cid], function (_export, _context) {
    return {
        setters: [function(_m) {
            var _exportObj = {};

            for (var _key in _m) {
              if (_key !== "default" && _key !== "__esModule") _exportObj[_key] = _m[_key];
            }
      
            _export(_exportObj);
        }],
        execute: function () { }
    };
    });
});